language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm run test
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: ctk+yl/OlAJ1uxonam/IbZiG7RnzNpQ7diBdrbt9CNOOUtXo5+4JqgAdnbuJ7UPeF1MvxFpCGQK29P0SCaL6xz6snQmfoyP8I6lYyVmD7wjIfC2SpvHx5+JUx+p+tLz6Sc/GefhwyODMzdQsjQ2SoBcjd1pe0j9zhzmaxE/r0KIa0xvNYlJnc4jdgJa/Wjhklp7Br9onvfhyS31NZn+5m3YNzP72woM9E0r0JzQv4s4LD4qnXmbUQRbdaIlLXmLbGSraO1EdbNC7f3RGbt+06HIKRFS0D/VzsdMBn3K5QOi5WjsJMongxNhzeM/b8lmpl+ZIF6m2XwZBn1PmeVuBtzcm3FD8C60MMEWAdl65mpMiZIYJ5KUTI2oUMrC1y3NhDrlSjT6UDO1sn8YmY5UTTEvgVnDpPJ6XGpEx5TvvBgm90Bxo3nuKLzMfhJes4fzZOFjsWX9cmAB6TJF3fl5FEvoBN5BpM4DAvOHKv/aDB0XjIA8b16XOfOkijzOWWGqn687BZYU55DeW+3mr5GiwFmEBErQbhEeKH03fpEO+E8FY9HVrOlFH73CsJ064qAmyMDuyksFED98JuxmuGM1Z5iTEcy786yDCTqlCbYP8ivzA3J71HLNUAsWDEICBsVh3Wmf5gfqTvJWd5uJI+0rdDiKsmnfLwTnZhsC5//SRCns=
  app:
    develop: cicd-2020-staging
