language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm run test
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: N9PM8vCliZm8pBSCKQqUnKcVw9PsJd6Obn5nRFErFAqOpycYtokJBWIbdtd3d3xC7Tl7EHA9Nd3oyDFwffmj1AXw8/0zmwf1HSatD1tCPWFUlAi/0iU6H6w7BYJsTRh9DA0iimTCIkPj8V9mY43wCrMTPCKzQr3pp+Tnyyj9vazbPmDj+wxFMlHwW3x51HbMpL2dZibDJNNPaDzUnZAn9B9D1hftI2fMeWQSj8a8Om4ofQa2POKKS/pU3tlZaAE0wFgW8GsmCaIsSiUVINbbfWJvyjpixiYJYlvUs51NFBKvsbM4SPJfc/9ivuAfD1PcWB0E4zuZfOezWXFInmiPQoemCa3vDBzo/+y/T+Rjnrlfqa7JJS68glsDbAU2X5Ijqu/SF0I3in+bLm4fuKKxogj7jol9DrAHvJI8qIWCoVpfyxU8AJOtifKPJxkY34+uSJYwZvbN+lZQzj7TKCB5hTpjp/i3azPcUBIsWpnrnxzURwjQLxgZ9QZj8j8JHMTkXmnyzWPV40uKEL85y9LlVFikL7FoTqbT3wkyNwN+Ay74HCM9+vb6xY/MxGiwSLUNgeatPvO/hujfqz+fa/SWakjWgsp/AKiCRNHtU4P+ZdJDSdCH8TOrHVyYcue8rTcpHY7QSWFJTXvBl+z3IyE4LsaRaz0f+ZLBZMiqXw8p3Vo=
  app:
    develop: cicd-2020-staging
