language: node_js
node_js:
  - 10.13.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - develop
deploy:
  provider: heroku
  api_key:
    secure: aRwE2ErrDFzokCBRWsyQqT+lCwp/LUmujx8AaVeAA2jj3QSe8aOh5aLow8XHGTzM925L15pHadM5p1B7vOveT/mJjGumcyNzkPwCRezu31O1hgdC6sOMkLmZdMGl+pd/netCXs7VKrKYQKXmF1A4VOsyOIZSJFhIZl+9WKtKfd1hT8PdD7D7RlZg2/emje7InHseaTxshGk53f+KjFryQ8e144NzvyJjodWlvsMP4U3IomPzUrlQ4d3vDYCm6Zfkf8CrmD1VhZtGCLyje4eWif2tiln2E/arb33bviFwayXv6pgSMSJhtY/cVWRSGWdzP4rDPoosRWgH6Tn+AFRjG4G0EzGJch3YCGqari/Mkeq9+P9y1g6Z2X/xd0aFU5V7VtRyu8uaNoBTqRUQK6yx7YZNLlizX/aCjHITXMwykAO9RWZT80pjoCvalRuhENmBTip0Wx8f91MTtQEEf0KmYSZrzpDFqKV/2rhvmSu+XOMM5zTHdnvl/XLdXp2Marc3tU7k9mqedHcfxiqOqOQ44WWWgRcp1LsjsDdUJBZ6vM/VVhx2/SlLqrx4rEWRL2N3OgM9wxKpVbn444HNX8i1/wfvdDjrmrZZTpAwYZBpC74C6l8NMFS/K2ZOxbQTfJr9JRul1SC1SuHX1k/FLaQVrjpYEP49WYOUUWClavhU5GU=
  app:
    develop: cicd-2020-staging
